In [2]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])

In [4]:
x[1]

array([3, 4])

In [5]:
x[1,:]

array([3, 4])

In [6]:
x[:,1]

array([2, 4, 6, 8])

In [7]:
a = x[2,:]

In [8]:
a

array([5, 6])

In [9]:
a[0]=25

In [11]:
np.float64

SyntaxError: invalid syntax (<ipython-input-11-df0eca0bfa5c>, line 1)